SETTINGS_BUTTON_TEXT = "🔧Settings"
BALANCE_BUTTON_TEXT = "💰Balance"
ACCOUNTS_BUTTON_TEXT = "🤖Accounts"

ADD_ACCOUNT_BUTTON_TEXT = "➕"
ADD_ACCOUNT_BUTTON_DATA = "add_account"

REMOVE_ACCOUNT_BUTTON_TEXT = "➖"
REMOVE_ACCOUNT_BUTTON_DATA = "remove_account"

LIST_ACCOUNTS_BUTTON_TEXT = "📜"
LIST_ACCOUNTS_BUTTON_DATA = "list_accounts"

BACK_BUTTON_TEXT = "<< Back"
BACK_BUTTON_DATA = "back"

ADD_ACCOUNT_CONFIRMATION_YES_TEXT = "➕"
ADD_ACCOUNT_CONFIRMATION_YES_DATA = "add_account_yes"

ADD_ACCOUNT_CONFIRMATION_NO_TEXT = "➖"
ADD_ACCOUNT_CONFIRMATION_NO_DATA = "add_account_no"

START_BOT_TEXT = "🏁Start bot"
STOP_BOT_TEXT = "🛑Stop bot"
